### ISSUE TITLE
iot.proto does not include parker.proto

### ISSUE THREAD

**Issue by akshephard** [gtfierro/xboswave#23]
I noticed the latest version of iot.proto does not include parker.proto as well as the XBOSIoTDeviceState message for the parker device. Is the idea that each installation will add the appropriate messages and modify iot.proto for their specific needs? If this is the case I will not modify iot.proto in my next pull request for our power meter.

**Comment by gtfierro** [comment]
`parker.proto` is a vendor-specific interface and has been moved to the appropriate location in the `xbos.proto` file: https://github.com/gtfierro/xboswave/blob/master/proto/xbos.proto#L46. You can modify `iot.proto` in future pull requests, but the file should remain somewhat vendor-agnostic. Does that help?

**Comment by gtfierro** [comment]
Following up on this; were you able to get this addressed? After the reorganization I did, the proto files shouldn't change in backwards-incompatible ways again. Sorry for that
