### ISSUE TITLE
xbosmortard for influxDB does not return data for requested start and end datetime

### ISSUE THREAD

**Issue by anandkp92** [gtfierro/xboswave#39]
Hi Gabe,

When I request for `2018-01-01T00:00:00Z` to `2018-01-02T00:00:00Z`, I only get data from `2018-01-01T00:05:00Z` (assuming I have data at every 5 minute interval) until `2018-01-01T23:55:00Z`, without the start and the end times. This is because you've used '>' and '<' instead of '>=' and '<=' [here](https://git.sr.ht/~gabe/mortar/tree/master/stages/influxdb.go#L157-162). 

Now, I can handle this on my end as well. But I wanted to bring this to your attention, because I believe it is inconsistent with BtrDB (when I query BtrDB, the start time is included in the data, right?). Let me know what you think and if you're planning on changing this or if I should handle it. 

Thanks
Anand

**Comment by gtfierro** [comment]
The behavior for BTrDB Is inclusive start, exclusive end. I think changing
the InfluxDB driver to match that behavior is a good idea. Would you be
able to make and test those changes and submit that as a pull request? It
should probably just boil down to choosing the right comparison operator in
the query, but I'm on my phone right now and can't easily check the
implementation

**Comment by anandkp92** [comment]
Sure! Working on it now!

**Comment by anandkp92** [comment]
Hi Gabe,

Apologies for the delay. I faced some difficulties navigating through sourcehut. 
And I still wasn't able to submit a pull request(!!) but I am attaching a patch for the fix, hoping that you can apply it and make a new release. I tested it locally and it worked. 

Thanks
Anand


[0001-updated-influx-query-to-be-inclusive-of-start-dateti.patch.zip](https://github.com/gtfierro/xboswave/files/3385304/0001-updated-influx-query-to-be-inclusive-of-start-dateti.patch.zip)

**Comment by gtfierro** [comment]
Why not submit it as a PR to xbosmortard?

**Comment by anandkp92** [comment]
What file do I change? 

As far as I understand, the query is happening in the stages/influxdb.go. So are you asking me to raise a pull request to update the go module version in xbosmortard/go.mod?

**Comment by gtfierro** [comment]
Oh, right. Just do a PR against https://github.com/SoftwareDefinedBuildings/mortar

**Comment by anandkp92** [comment]
Done!
