### ISSUE TITLE
ingester.yml should be ingester.template

### ISSUE THREAD

**Issue by akshephard** [gtfierro/xboswave#6]
To prevent overwriting config files which are actually filled out when merging changes from upstream the template config file should not be named the same as the one actually used.

**Comment by gtfierro** [comment]
I'm of a different mind here. I think its a better solution to copy the `ingester.yml` file to a dedicated location that isn't the same as the "development" version (e.g. `/etc/ingester/ingester.yml`), and then point the `ingester` process to that file. In a real deployment, you likely aren't going to be running the ingester by building the binary from source and executing from the repo directory.

This requires having the ingester take the configuration file as an argument, which is a simple fix

**Comment by gtfierro** [comment]
https://github.com/gtfierro/xboswave/commit/671ada7f9ac7e6e9b2ce7e75b0ff1fd43201aa13

**Comment by akshephard** [comment]
Ah okay. I'm assuming you are of the same mindset for the driver config files as well?

**Comment by gtfierro** [comment]
Definitely! Nothing should execute out of the git repo

**Comment by gtfierro** [comment]
Definitely! Nothing should execute out of the git repo
